#!/usr/bin/env python3
"""Phase 1 sanity figure: does the physics behave the way a welder expects?

Six panels, all generated by running the code in this repository:

1. Goldak double-ellipsoid power density on the plate surface.
2. Rosenthal melt isotherm cross-section vs. the reduced-order model's
   half-ellipse at the same heat input — the ROM's geometric anchor.
3. Steady-state penetration maps: gap sweep and travel-speed sweep, with the
   target band and the burn-through onset marked.
4. A full WeldCell run over a stepped gap: gap profile and true penetration.
5. The raw 5 kHz V/I waveform, zoomed until short circuits are visible.
6. The voltage spectrum — the pool-oscillation peak that the whole
   "power source as a sensor" claim rests on.

Usage::

    python scripts/plot_physics.py --seed 0 --out out/phase1_physics.png
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # run without installing

import matplotlib.pyplot as plt
import numpy as np

from weldloop.config import default_config
from weldloop.physics import arc as arcmod
from weldloop.physics import heat_source as hs
from weldloop.physics.melt_pool import MeltPoolModel, PoolInputs
from weldloop.sim.cell import WeldCell
from weldloop.viz.style import C, band, downsample, shade_flag, use_style


def _inputs(cfg, *, I=230.0, v=4.5e-3, gap=0.0, weave=0.0):
    V = arcmod.arc_voltage(I, cfg.arc.L_arc_ref, 15.0e-3, cfg.arc, cfg.consumable)
    return PoolInputs(
        I=I,
        V=V,
        v_travel=v,
        v_wire=arcmod.melting_rate(I, 15.0e-3, cfg.arc),
        gap=gap,
        thickness=cfg.joint.thickness,
        weave_amp=weave,
    )


# --------------------------------------------------------------------------
def panel_goldak(ax, cfg) -> None:
    g = hs.GoldakParams()
    xi = np.linspace(-4.0 * g.a_r, 4.0 * g.a_f, 300)
    y = np.linspace(-3.0 * g.b, 3.0 * g.b, 300)
    X, Y = np.meshgrid(xi, y, indexing="ij")
    q = hs.goldak_flux(X, Y, np.zeros_like(X), 5000.0, g)
    from matplotlib.colors import PowerNorm

    mesh = ax.pcolormesh(
        X * 1e3, Y * 1e3, q * 1e-9,
        cmap="inferno", shading="auto", norm=PowerNorm(0.35),
    )
    cb = ax.figure.colorbar(mesh, ax=ax, pad=0.015, fraction=0.045)
    cb.set_label("power density [GW/m³]", color=C.text, fontsize=8)
    cb.ax.tick_params(colors=C.muted, labelsize=7)
    cb.outline.set_edgecolor(C.grid)
    ax.set_title("Goldak 双椭球热源 (z=0 表面, 5 kW)")
    ax.set_xlabel("travel direction ξ [mm]   (ξ>0 = ahead of arc)")
    ax.set_ylabel("y [mm]")
    ax.set_ylim(-16.0, 16.0)
    ax.grid(False)
    ax.axvline(0.0, color=C.text, lw=0.8, alpha=0.6, ls="--")
    ax.text(
        0.02, 0.95,
        "拖尾在后（a_r = 4·a_f）：\n熔池被焊枪拖在身后",
        transform=ax.transAxes, color=C.text, fontsize=8, va="top",
    )


def panel_isotherm(ax, cfg) -> None:
    """Rosenthal fusion boundary vs the ROM's assumed half-ellipse."""
    mat = cfg.material
    model = MeltPoolModel(cfg)
    u = _inputs(cfg)
    Q = cfg.pool.eta_arc * u.V * u.I
    v = u.v_travel

    # Rosenthal: trace the T = T_m contour in the (y, z) plane of maximum width
    ys = np.linspace(0.0, 9.0e-3, 260)
    zs = np.linspace(0.0, 9.0e-3, 260)
    Y, Z = np.meshgrid(ys, zs, indexing="ij")
    T = np.array(
        [[hs._max_T_at(float(yy), float(zz), Q, v, mat) for zz in zs] for yy in ys]
    )
    ax.contour(
        np.concatenate([-Y[::-1], Y]) * 1e3,
        np.concatenate([Z[::-1], Z]) * 1e3,
        np.concatenate([T[::-1], T]),
        levels=[mat.T_m],
        colors=[C.aux2],
        linewidths=1.6,
    )

    s = model.steady_state(u)
    th = np.linspace(0.0, math.pi, 200)
    ax.plot(
        0.5 * s.w * 1e3 * np.cos(th), s.p * 1e3 * np.sin(th),
        color=C.adaptive, lw=1.8,
    )
    ax.axhline(
        cfg.joint.thickness * 1e3, color=C.bad, lw=1.2, ls="--",
    )
    ax.text(
        -8.6, cfg.joint.thickness * 1e3 + 0.25, "plate thickness 6 mm",
        color=C.bad, fontsize=7.5,
    )
    ax.plot([], [], color=C.aux2, lw=1.6, label="Rosenthal 熔合等温线 (解析)")
    ax.plot([], [], color=C.adaptive, lw=1.8, label="降阶模型半椭圆 (稳态)")
    ax.set_ylim(7.4, -0.4)
    ax.set_xlim(-9.0, 9.0)
    ax.text(
        0.015, 0.06,
        "点热源预测的熔池比实际 GMAW 焊道更窄更深；\n降阶模型用宽深比 AR 修正，AR 由电流/速度/摆动/间隙决定",
        transform=ax.transAxes, color=C.muted, fontsize=7.5,
    )
    ax.set_title(f"熔池截面锚点  ({u.I:.0f} A, {v*1e3:.1f} mm/s, gap 0)")
    ax.set_xlabel("y [mm]")
    ax.set_ylabel("depth [mm]")
    ax.legend(loc="lower right")


def panel_maps(ax, cfg) -> None:
    model = MeltPoolModel(cfg)
    gaps = np.linspace(0.0, 4.5e-3, 19)
    p_gap, bt = [], []
    for g in gaps:
        u = _inputs(cfg, gap=float(g))
        st = model.steady_state(u)
        p_gap.append(st.p * 1e3)
        bt.append(model.defects(st, u).burn_through)
    p_gap = np.asarray(p_gap)
    bt = np.asarray(bt)

    band(ax, cfg.control.p_lo * 1e3, cfg.control.p_hi * 1e3, label="目标带 3–5 mm")
    ax.plot(gaps * 1e3, p_gap, color=C.baseline, marker="o", ms=3, label="定参数 (baseline)")
    if bt.any():
        first = float(gaps[np.argmax(bt)] * 1e3)
        ax.axvline(first, color=C.bad, lw=1.2, ls="--")
        ax.text(
            first + 0.06, 3.2, f"烧穿起点\ngap = {first:.1f} mm",
            color=C.bad, fontsize=7.5,
        )
    ax.scatter(
        gaps[bt] * 1e3, p_gap[bt], color=C.bad, s=26, zorder=5, label="burn-through"
    )
    ax.axhline(cfg.joint.thickness * 1e3, color=C.muted, lw=1.0, ls=":")
    ax.set_title("稳态熔深 vs 坡口间隙（固定工艺参数）")
    ax.set_xlabel("root gap [mm]")
    ax.set_ylabel("penetration [mm]")
    ax.legend(loc="upper left")


def panel_handles(ax, cfg) -> None:
    """What authority does the motion layer actually have at a 4 mm gap?"""
    model = MeltPoolModel(cfg)
    speeds = np.linspace(3.0e-3, 11.0e-3, 17)
    for weave, color, lab in (
        (0.0, C.baseline, "no weave"),
        (1.5e-3, C.aux, "weave 1.5 mm"),
        (2.5e-3, C.adaptive, "weave 2.5 mm"),
    ):
        ps = [
            model.steady_state(_inputs(cfg, v=float(v), gap=4.0e-3, weave=weave)).p * 1e3
            for v in speeds
        ]
        ax.plot(speeds * 1e3, ps, color=color, marker="o", ms=2.6, label=lab)
    band(ax, cfg.control.p_lo * 1e3, cfg.control.p_hi * 1e3)
    ax.axvline(cfg.baseline.v_travel * 1e3, color=C.muted, ls=":", lw=1.0)
    ax.text(
        cfg.baseline.v_travel * 1e3 + 0.1, 6.0, "baseline speed",
        color=C.muted, fontsize=7.5,
    )
    ax.set_title("控制权限 @ gap = 4 mm：速度弱、摆动强")
    ax.set_xlabel("travel speed [mm/s]")
    ax.set_ylabel("penetration [mm]")
    ax.legend(loc="upper right")


def panel_run(ax, run) -> None:
    s, gap, p, btf = downsample(run["s"], run["gap"], run["p"], run["bt"])
    shade_flag(ax, s * 1e3, btf > 0.5, label="burn-through")
    ax.plot(s * 1e3, gap * 1e3, color=C.aux2, lw=1.3, label="root gap g(s)")
    ax.plot(s * 1e3, p * 1e3, color=C.adaptive, lw=1.6, label="true penetration")
    cfg = run["cfg"]
    band(ax, cfg.control.p_lo * 1e3, cfg.control.p_hi * 1e3)
    ax.axhline(cfg.joint.thickness * 1e3, color=C.muted, ls=":", lw=1.0)
    ax.set_title("WeldCell 全程仿真：阶跃间隙下定参数焊接")
    ax.set_xlabel("position along seam s [mm]")
    ax.set_ylabel("[mm]")
    ax.legend(loc="upper left", ncols=3)


def panel_waveform(ax, run) -> None:
    cfg = run["cfg"]
    dt = cfg.sim.dt
    n0 = len(run["V"]) // 2
    n = int(0.12 / dt)  # 120 ms window
    t = np.arange(n) * dt * 1e3
    V = run["V"][n0 : n0 + n]
    I = run["I"][n0 : n0 + n]
    shade_flag(ax, t, run["short"][n0 : n0 + n] > 0.5, color=C.bad, alpha=0.18)
    ax.plot(t, V, color=C.aux2, lw=0.9, label="arc voltage V")
    ax.set_ylabel("V [V]", color=C.aux2)
    ax.set_xlabel("time [ms]  (window from mid-seam)")
    ax2 = ax.twinx()
    ax2.plot(t, I, color=C.warn, lw=0.8, alpha=0.85, label="current I")
    ax2.set_ylabel("I [A]", color=C.warn)
    ax2.grid(False)
    ax2.tick_params(colors=C.warn)
    ax.tick_params(axis="y", colors=C.aux2)
    f_osc = float(np.median(run["f_osc"][n0 : n0 + n]))
    ax.set_ylim(0.0, 32.0)
    ax2.set_ylim(150.0, 420.0)
    ax.set_title("原始 5 kHz 波形：熔池振荡纹波 + 短路事件")
    ax.text(
        0.012, 0.93,
        f"红色区间 = 短路：V 塌到 {cfg.arc.V_short:.0f} V，I 冲高 ×{cfg.arc.I_short_gain:.1f}\n"
        f"其余时间 V/I 上的规则纹波 = 熔池表面振荡 (f_osc ≈ {f_osc:.0f} Hz) —— 这才是熔深信号",
        transform=ax.transAxes, color=C.text, fontsize=8.5, va="top",
    )


def panel_spectrum(ax, run) -> None:
    cfg = run["cfg"]
    n = 16384
    V = run["V"][-n:].copy()
    short = run["short"][-n:] > 0.5
    idx = np.arange(n)
    # blank the short circuits: a 20 V collapse would bury a 0.4 V ripple
    V[short] = np.interp(idx[short], idx[~short], V[~short])
    V -= V.mean()
    spec = np.abs(np.fft.rfft(V * np.hanning(n))) / n
    freqs = np.fft.rfftfreq(n, cfg.sim.dt)
    m = (freqs > 5.0) & (freqs < 500.0)
    ax.semilogy(freqs[m], spec[m], color=C.adaptive, lw=1.1)
    f_true = float(np.median(run["f_osc"][-n:]))
    ax.axvline(f_true, color=C.aux2, ls="--", lw=1.2)
    ax.text(
        f_true + 8, spec[m].max() * 0.5,
        f"pool oscillation\nf_osc = {f_true:.0f} Hz",
        color=C.aux2, fontsize=8,
    )
    ax.set_title("电压频谱：熔池振荡峰 = 熔深/熔宽的可观测通道")
    ax.set_xlabel("frequency [Hz]")
    ax.set_ylabel("|V| [V/bin]")


# --------------------------------------------------------------------------
def simulate(cfg) -> dict:
    cell = WeldCell(cfg, seed=cfg.sim.seed)
    rows = [
        (
            g.s, g.gap, g.pool.p, g.pool.w, g.arc.V, g.arc.I,
            float(g.defects.burn_through), float(g.arc.in_short), g.arc.f_osc,
        )
        for g in cell.run()
    ]
    a = np.asarray(rows, dtype=float)
    keys = ["s", "gap", "p", "w", "V", "I", "bt", "short", "f_osc"]
    out = {k: a[:, i] for i, k in enumerate(keys)}
    out["cfg"] = cfg
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--out", type=Path, default=Path("out/phase1_physics.png"))
    args = ap.parse_args()

    cfg = default_config(seam__kind="step", seam__length=0.20, sim__seed=args.seed)
    use_style()
    run = simulate(cfg)

    fig, axes = plt.subplots(3, 2, figsize=(15.5, 12.5))
    panel_goldak(axes[0, 0], cfg)
    panel_isotherm(axes[0, 1], cfg)
    panel_maps(axes[1, 0], cfg)
    panel_handles(axes[1, 1], cfg)
    panel_run(axes[2, 0], run)
    panel_spectrum(axes[2, 1], run)

    fig.suptitle(
        "weldloop Phase 1 — 物理模型与仿真单元自检   "
        f"(seed={args.seed}, 6 mm 低碳钢对接, {cfg.baseline.I_set:.0f} A)",
        color=C.text, fontsize=13, fontweight="bold", y=0.995,
    )
    fig.tight_layout(rect=(0, 0, 1, 0.985))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(args.out, dpi=130)
    print(f"wrote {args.out}")

    # second, smaller figure: the raw waveform deserves its own width
    fig2, ax = plt.subplots(1, 1, figsize=(15.5, 3.6))
    panel_waveform(ax, run)
    fig2.tight_layout()
    out2 = args.out.with_name(args.out.stem + "_waveform.png")
    fig2.savefig(out2, dpi=130)
    print(f"wrote {out2}")


if __name__ == "__main__":
    main()
